### PR TITLE
Make script windows compatible

### PR DESCRIPTION
**Pull request by andreifilip123**

### CODE REVIEW

**Comment by alexisveryreal** [comment]
Hello, I ran this and got the following

```shell
pnpm install
```
- removed diff 5.10.3..6.0.1-tailwind from existing-diffs.json
- removed diff-5.10.3-6.0.1-tailwind.patch from the diffs folder

```shell
pn generate-all-missing-diffs
                                                                            fs
> t3-upgrade-diffs@0.1.0 generate-all-missing-diffs G:\dev\create-t3-app-diffs
> tsx src/runGenerateAllScript.ts

Generating all missing diffs
Failed to parse version 5.8.0-next                                          tailwind\upgrade/ \tmp\5.10.3..6.0.1-tailwind\current/  
Found 1 new diffs
Error: Command failed: rsync -a --delete --exclude=.git/ \tmp\5.10.3..6.0.1-tailwind\upgrade/ \tmp\5.10.3..6.0.1-tailwind\current/
'rsync' is not recognized as an internal or external command,
operable program or batch file.

    at __node_internal_genericNodeError (node:internal/errors:868:15)       
    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {    
  code: 1,                                                                  rade/ \\tmp\\5.10.3..6.0.1-tailwind\\current/'
  killed: false,
  signal: null,
  cmd: 'rsync -a --delete --exclude=.git/ \\tmp\\5.10.3..6.0.1-tailwind\\upgrade/ \\tmp\\5.10.3..6.0.1-tailwind\\current/'
}
Generated batch: 1
Batch took 93115.31309999898ms. 0 left
Done!
```

From what I can tell, rsync would be something I have to download on my windows machine I imagine? Though from my short research not sure if it would work the same.

Let me know if you need any more testing though!

**Comment by andreifilip123** [comment]
@alexisveryreal can you try again now ? I replaced rsync with pbcopy on windows and it should work fine

**Comment by alexisveryreal** [comment]
@andreifilip123 

seems to be working now!

```shell
pn generate-all-missing-diffs

> t3-upgrade-diffs@0.1.0 generate-all-missing-diffs G:\dev\create-t3-app-diffs
> tsx src/runGenerateAllScript.ts

Generating all missing diffs
Failed to parse version 5.8.0-next
Found 1 new diffs
Generated diff: 5.10.3..6.0.1-tailwind
Generated batch: 1
Batch took 77785.52689999714ms. 0 left
Done!
```

Though i'm not sure if existing-diffs.json is supposed to be updated as well?

**Comment by andreifilip123** [comment]
Yep. Made that in a separate PR

**Pull request merged**
